[project]
name = "workshop-improving-r-in-rag"
version = "0.1.0"
description = "This workshop focuses on enhancing the Retrieval component in Retrieval Augmented Generation (RAG) systems."
authors = [
    { name = "Kacper Łukawski", email = "kacper.lukawski@qdrant.com" }
]
requires-python = ">=3.12"
dependencies = [
    "any-llm-sdk[all]>=0.20.2",
    "fastembed>=0.7.3",
    "jupyter>=1.1.1",
    "python-dotenv>=1.1.1",
    "qdrant-client>=1.15.1",
]
